export const GET_CURRENT_USER_PROFILE_REQUEST = "GET_CURRENT_USER_PROFILE_REQUEST";
export const GET_CURRENT_USER_PROFILE_SUCCESS = " GET_CURRENT_USER_PROFILE_SUCCESS";
export const GET_CURRENT_USER_PROFILE_FAIL = " GET_CURRENT_USER_PROFILE_FAIL";
export const GET_CURRENT_USER_PROFILE_RESET = " GET_CURRENT_USER_PROFILE_RESET";